### ISSUE TITLE
Changing Application Routing Rule crashes DAW (Reaper)

### ISSUE THREAD

**Issue by emckenna** [eiz/SynchronousAudioRouter#10]
I recently wanted to edit an app routing rule and found that I could not edit or delete anything.  I was able to change the values, but nothing was saved, and Reaper would crash after clicking OK after making any changes.  I can provide any other information needed, just not sure what to provide.

And Thank you, I use SAR with Reaper.fm and its been a great help to me.

**Comment by eiz** [comment]
Could you please attach a copy of your SAR config file? It is located at %APPDATA%\SynchronousAudioRouter\default.json.

**Comment by emckenna** [comment]
let me verify its still and issue.. there have been a few Reaper updates since I posted this.

**Comment by emckenna** [comment]
Here's a pastebin of my default.json file.

http://pastebin.com/uDBmvBCp

**Comment by emckenna** [comment]
so.. dont know why it did not occur to me sooner, but editing the default.json file works fine.  It's just the GUI that might not be able to save the file.  If you want.. I could do a screen capture to show you what I'm seeing.

**Comment by eiz** [comment]
Sorry for the delay in responding. I loaded your config and I am able to edit and add items without any crash, but I did notice a bug -- if you have more routing rules than endpoints, you can't delete any items in the list after the # of endpoints due to a bad bounds check. That's fixed in 02cdc8948a99c738f3e31d791ade2bd2aec26c0d.

**Comment by eiz** [comment]
I'm going to consider this matter resolved unless I get feedback indicating otherwise. There is a test build in issue #13 that contains the fix for this.
