### ISSUE TITLE
What is Mackenzie Straight?

### ISSUE THREAD

**Issue by jerryemery** [eiz/SynchronousAudioRouter#103]
When attempting to install SAR, a pop-up ask if I would like to install "Many Worlds Sound" published by Mackenzie Straight.  If I chose "no," SAR will not complete installation.  This pop-up from "Mackenzie Straight" has the MOD of a virus hack.  Anyone know what it is?

**Comment by paulheu** [comment]
It's the driver needed to run SAR..
