### ISSUE TITLE
Newest build won't install

### ISSUE THREAD

**Issue by iPlayTheKazoo** [eiz/SynchronousAudioRouter#106]
I'm trying to install [the latest build](https://ci.appveyor.com/api/buildjobs/c7kksm044mf7kpte/artifacts/SarInstaller%2Fbin%2Fx64%2FRelease%2FSynchronousAudioRouter_x64.msi) from AppVeyor. When I do this however, I get this error:

![image](https://user-images.githubusercontent.com/66897086/100160098-42cfc800-2eaf-11eb-8591-4c651dc70567.png)

What went wrong?

**Comment by platform-717** [comment]
Check this, it will work: https://github.com/eiz/SynchronousAudioRouter/issues/86#issuecomment-620964907.
