### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by veins1** [eiz/SynchronousAudioRouter#11]
Hi, can you please compile and upload a new build?

**Comment by danielformosa0908** [comment]
i second this! SAR doesn't work on windows 10 and its making me sad :(

**Comment by eiz** [comment]
@veins1 it's coming, but is there a specific reason you're asking?

**Comment by veins1** [comment]
@eiz Yep. My Studio One only opens once and I have to delete SAR or restart my pc to open it again. Also if I use SAR and host crashes, it doesn't completely exits and just hangs there eating memory and I have no audio cos it's still using ASIO. Those are two main reasons.
I also tried to compile myself, installed it, control panel was working but no audio. Reinstalled last uploaded build and not FL doesn't work with SAR.

**Comment by eiz** [comment]
I'm currently not able to reproduce that with Studio One 3.3.4.41933, using either SAR 0.12 or the current master. I did encounter some issues with a prior install of it last year while working on a different problem (you couldn't access the SAR control panel unless you already had endpoints configured using other software), but it's currently working fine. If you could let me know the following:

- Your installed Studio One version, including 32/64-bitness of it
- Your audio interface
- Your current Windows OS build

It may help to understand what's going wrong for you. Have you tried using another DAW, and did that also fail in the same way?

One more thing, you may want to try this debug build: [SynchronousAudioRouter-20160511-debug.zip](https://github.com/eiz/SynchronousAudioRouter/files/259446/SynchronousAudioRouter-20160511-debug.zip). It will produce log files in your %APPDATA%\SynchronousAudioRouter\logs directory which may be useful.

**Comment by veins1** [comment]
@eiz 

> I assume if you look in your process list in taskmgr after exiting, the process is still there and unkillable.
Yes. And it's not only Studio One but the same happened with Reaper.

**Comment by pannal** [comment]
There seems to have been serious development since the last official release. Can we expect a new beta soon?

**Comment by ToxMox** [comment]
@eiz Mackenzie,
I just also wanted to say how great SAR is. I've tried Chevolume and Audiorouter and they were both super buggy and have been abandoned. SAR is quite wonderful and with the regex filtering I can make all Steam games redirect to a virtual cable.. Would love to donate or something to help development. I appreciate the work you've put into this.

**Comment by cjunekim** [comment]
I love SAR! It's much better than most of the alternatives. I really appreciate your effort.

It's been almost 2 years since the official release is done. Will the new version get released soon?
