### ISSUE TITLE
v0.13.2 release notes improvements

### ISSUE THREAD

**Issue by ramonsmits** [eiz/SynchronousAudioRouter#110]
I just [compared 0.13.1 with 0.13.2](https://github.com/eiz/SynchronousAudioRouter/compare/v0.13.1...v0.13.2) and seems it has some actual bug fixes by @amurzeau:

Driver: fix IRP leak and client process hang …
Driver: unmap section when controlContext is destroyed …
Driver: Enable POOL_NX_OPTIN …
Driver IOCTL: Use consistent KS/SAR dispatch …
Driver: Add topology filter and dynamic channel count …
Driver: fixup some things …
Driver: remove unused clockRegister. …
SarAsio: Fix crash in case of threaded bufferSwitch(tick) …
SarAsio: Handle different type of sample …
SarAsio: fix SetupDiGetClassDevs leak …
Driver: add more logs with levels
SarAsio: Fix buffer overrun
SarAsio: use std::wstring for descriptions and paths (#53)

Maybe useful to add this to the release notes? Maybe including the comparison link for convenience?

Specifically, I seem to be experiencing the *IRP leak and client process hang*.

**Comment by amurzeau** [comment]
Thanks, I've added more information with commits since the 0.13.1 release.
Is it ok for you ?
https://github.com/eiz/SynchronousAudioRouter/releases/tag/v0.13.2

**Comment by ramonsmits** [comment]
> Thanks, I've added more information with commits since the 0.13.1 release.
> Is it ok for you ?

I was already aware :-) but this is for others that stumble upon the release.
