### ISSUE TITLE
First Signing

### ISSUE THREAD

**Issue by Krischkros** [eiz/SynchronousAudioRouter#112]
Hello,
i just saw all pre-releases are unsigned.
Any release date for a actual "release"-version planned?
Rebooting a PC for a driver everytime when you are not playing is kinda annoying.

**Comment by amurzeau** [comment]
See here: https://github.com/eiz/SynchronousAudioRouter/issues/86

**Comment by amurzeau** [comment]
The 0.13.2 version fixes the need to reboot the PC everytime, but also requires testsigning to be enabled.

**Comment by Claw256** [comment]
@amurzeau Does test signing have to be enabled all the time when using the driver, or only when installing?

**Comment by amurzeau** [comment]
You need to keep it enabled else Windows won't load SAR's driver
