### ISSUE TITLE
Wont work in WIN10?

### ISSUE THREAD

**Issue by danielformosa0908** [eiz/SynchronousAudioRouter#12]
i have tested this twice on 2 computers.
both using Reaper

pc1: had windows 7 and the SynchronousAudioRouter worked flawlessly! Then i had to upgrade to windows 10 so i could use a new capture device for my studio, and then i started getting the "Error initializing ASIO buffer" and im not 100% sure as to what may be causing this.

pc2: fresh install of both reaper and SynchronousAudioRouter and i set the ASIO up, and im gettign "Error starting ASIO"

i have been having this issue for the past 2 days, im all out of options. Hope you can help me !
Thank you !

**Comment by skaufhold** [comment]
I'm not sure this is strictly a Windows 10 issue - I'm using SAR successfully on a fully updated Win10 system.

Other possible reasons:

* Wonky interaction with your specific device driver
* Missing admin permissions - I'm assuming you checked, but can't hurt to mention it

Probably needs more info to solve.

**Comment by danielformosa0908** [comment]
I uninstalled Reaper ASIO4ALL and SAR then re installed in this order all with admin privelages

ASIO4ALL (right click run as admin)
SAR (Right click "Install")
Reaper (Right click Run as admin)

once all done, i set it up correctly then i ran reaper always as admin and it works!

Tested where i run normal, came up with an error, turned antivirus off, still had an error, but no mater what i have running if i open reaper with admin privileges it works flawlessly, but mind you i am doing this on my laptop at work and not on the computer that is of an importance! wish me luck and ill keep you all updated :)

**Comment by skaufhold** [comment]
The important part is that you open Reaper with admin privileges - SAR needs those, as stated in the setup instructions in the repository. Issue #9 contains some more details about why it is like that.

**Comment by eiz** [comment]
SAR does work in Windows 10. If you encounter more specific issues with the Windows 10 support other than the require admin thing (this will be optional in 0.13), please open a new issue with the details. Thanks.
