### ISSUE TITLE
WDF_VIOLATION bsod on input change

### ISSUE THREAD

**Issue by Luna-foxx** [eiz/SynchronousAudioRouter#123]
in fl-studio changing inputs to sar causes a bsod with WDF_VIOLATION as the error
i don't have any other info then that sorry
i tried to switch again after restarting and when switching, the PC will bsod
i had reinstalled windows about 2-3 weeks ago so i don't have a lot of drivers

**Comment by amurzeau** [comment]
which version did you used ?

**Comment by Luna-foxx** [comment]
audio interface was causing issues i will close this now
