### ISSUE TITLE
compilation guide

### ISSUE THREAD

**Issue by pkviet** [eiz/SynchronousAudioRouter#16]
Hello,
waiting impatiently for next release.
Until then could there be a compilation guide ?
thanks  a lot for this wonderful project.

**Comment by eiz** [comment]
SAR is a hobby project. There will be a new non-test release (see issue #13 for the current test build) when, and if, I get around to it. Doing a full release requires a lot of tedious testing work and I don't currently have a large amount of free time to devote to it.

As for a compilation guide, I have no plans to write such a document, but the general build requirements are VS2015, the WDK, and WiX 3.11.
