### ISSUE TITLE
The need for admin makes this app useless 

### ISSUE THREAD

**Issue by Ulf3000** [eiz/SynchronousAudioRouter#21]
i don´t know if i have already commented before , 

but starting your apps in admin mode means no drag and drop from a non admin prog to reaper ... 
starting firefox in admin mode ? not a good idea 

why don´t you just make your  virtual devices persistent ?

**Comment by eiz** [comment]
If you'd like different behavior, it's updated in master. There is a test build attached to issue #13.

I'm not going to change the creation process or persistence of virtual endpoints.

**Comment by Ulf3000** [comment]
hey thanx man thats working brilliant .. easy to record my usb mic and firefox in reaper now !!
