### ISSUE TITLE
Playback endpoints max out at 44kHz

### ISSUE THREAD

**Issue by emckenna** [eiz/SynchronousAudioRouter#25]
My sound card's lowest quality setting is 48hKz, but every endpoint I create displays 44kHz as its quality.

Don't want to debate the differences between 44 and 48, but thought they should be the same to minimize latency.  Is this an issue or should I just not worry about it.

**Comment by eiz** [comment]
SAR uses the same sample rate the underlying ASIO driver is opened with. It doesn't do (and isn't capable of) any kind of resampling.

**Comment by emckenna** [comment]
Gotcha.  I tried out a much newer headset and now have many more quality settings.
