### ISSUE TITLE
Paypal donation or charging?

### ISSUE THREAD

**Issue by cjunekim** [eiz/SynchronousAudioRouter#38]
Since the recent death of the author of ASIO Link, there are almost no alternatives remaining except SAR for using virtual audio devices on windows with low enough latency for real-time use on windows. Often used Voicemeeter cannot actually stand against the real time demand.

I know that Mr. Straight is busy but would it be possible to pay him to continue maintaining and improving this wonderful project? Paypal donation or charging, like reaper, maybe?

**Comment by eiz** [comment]
Short answer: I don't want your money. I'm banking solid cash as a software development manager at my day job. You can't materially compete with that unless you're running a business with real income that depends on SAR.

I'm more interested in hearing about your real use cases. I'm motivated by problem solving, not money.

**Comment by cjunekim** [comment]
Sorry that I didn't understand your true motivation. I just wanted to help your project going on. I appreciate your efforts.
