### ISSUE TITLE
ASIOCreateBuffers fails if no underlying hardware device is selected

### ISSUE THREAD

**Issue by cerebellum42** [eiz/SynchronousAudioRouter#4]
I've been trying to get the Router to work, but haven't had any success so far. Whenever I select the ASIO device in my DAW it aborts saying the device could not be initialized.

I'm on Windows 8.1 using Studio One 3, running with admin privileges as instructed. The underlying ASIO driver is the one that comes with the Focusrite Scarlett 2i4.

I restarted after installing (and reinstalling) the router and I've tried uninstalling any other programs that create windows audio devices or similar things.

I would love to provide a more detailed error, but I'm not getting any specific errors displayed and don't know if the driver keeps any crash logs.

Any ideas on what I could try to get it work or where to check for better error messages?

Update: I checked the Studio One log files, but they are not much more precise.

I get these two lines when selecting the Audio Router:

```
2016/02/15 20:59:11.125 [Warning] (asioservice): No outputs found in ASIO driver
2016/02/15 20:59:11.126 [Warning] (asioservice): No active ports for ASIO driver
```

**Comment by eiz** [comment]
SAR doesn't currently have particularly extensive logging but you can get some information by using the DebugView tool from Microsoft: https://technet.microsoft.com/en-us/sysinternals/debugview.aspx

Run as admin and enable global win32 capture. You should see messages from SarAsioWrapper (and possibly the Focusrite driver as well).

Are you using the 32 or 64 bit version of Studio One? And 32 or 64 bit version of Windows 8.1?

**Comment by cerebellum42** [comment]
64 bit windows, tried both versions of Studio One. In the meantime I tried it with another DAW and it's working (with a few UI issues, but otherwise totally fine), so it's most likely an issue with the combination of Studio One and the driver, not my system in general.

I think what might be happening is that Studio One expects the driver to report at least one port, but when the driver is first initialized none are returned since I didn't get a chance to select the Focusrite driver yet.

I'll try the DebugView tool though and report back with what I got.

**Comment by eiz** [comment]
Ah, I see the problem now. Studio One is not letting you access the ASIO control panel if the init fails. SAR currently requires a hardware device to be selected in order to open the device, because it mimics the supported sample rates and other parameters of the underlying device. Should be possible to implement a fix for this. If you open SAR in Studio One after having configured it with your other DAW, does it work?

**Comment by cerebellum42** [comment]
Yes, it does!
Well, it crashed once for an unknown reason and on subsequent starts it worked, so I'll assume that crash was probably unrelated. It also doesn't have the UI issues I get with Bitwig.
