### ISSUE TITLE
.13.1 won't install on Windows 10 1709

### ISSUE THREAD

**Issue by billhatter** [eiz/SynchronousAudioRouter#45]
I installed the latest driver (0_13_1), but it reports that it is unsigned in Windows 10 Pro version 1709.

**Comment by billhatter** [comment]
Yes, I have secure boot. I saw the readme after submitting the ticket. Any plans to get the driver certified?

Get Outlook for Android

________________________________

**Comment by eiz** [comment]
Unfortunately doing so requires an EV signing certificate, which I do not have, and do not plan on paying the ~$450 fee for.
