### ISSUE TITLE
Dropdownlist does not drop down on windows 10

### ISSUE THREAD

**Issue by kdejaeger** [eiz/SynchronousAudioRouter#56]
I installed this on windows 10. Have a realtek and ni s8 asio driver. But the selection box 'hardware interface' remains empty.

**Comment by kdejaeger** [comment]
Disabled secure boot, still the same.

**Comment by cdhowie** [comment]
I've noticed that the dropdowns on Windows 10 have very little height.  You can use the keyboard up and down arrow keys to select different drivers after expanding the dropdown box.

**Comment by kdejaeger** [comment]
Heeey you smart ass :). You're right. Tnx for the tip :)
