### ISSUE TITLE
No Audio Routed With UMC ASIO Driver

### ISSUE THREAD

**Issue by Jonatino** [eiz/SynchronousAudioRouter#68]
Trying to get the output from my ASIO driver to show up in another recording device but no matter what I try there is no sound going to it.

Things I've tried:
1. Running reaper as admin
2. Reinstall SAR
3. Reboot pc
4. Turn off safe mode in ASIO driver

Heres the setup
![](https://dl.dropboxusercontent.com/s/t3oe5uu6hmxppwm/explorer_2019-04-03_22-38-58.png)

And when I start talking there is no output on the SAR recording device
![](https://dl.dropboxusercontent.com/s/8xub833bz4oe4il/explorer_2019-04-03_22-40-46.png)

Please help!

**Comment by TekSoup** [comment]
there is a asio re-route option in Reaper, it is easy to miss, you only see it in the options when you do advanced install, it works great!

**Comment by TekSoup** [comment]
Mine don't, I use a u/a apollo quad . I use to use a behringer with it. They should stay, save your project. And it should.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
