### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by raejlong** [eiz/SynchronousAudioRouter#75]
Uninstalling 
Windows 7
Driver Manager: Removed SynchronousAudio
Used both Windows Program Uninstall AND Synchronous.msi to uninstall

CANNOT remove SynchronousAudioRouter.sys from windows\system32\drivers

The uninstaller leaves this in the registry and in the drivers folder in system 32

Can you provide an uninstaller please?

**Comment by amurzeau** [comment]
I've modified the installer to remove more stuff when uninstalling.
I still think some stuff are left in the registry related to windows endpoint setting caches depending on the Windows version used.

The installer is available here: https://github.com/amurzeau/SynchronousAudioRouter/releases/tag/v0.13.99.2-amurzeau

The driver is not signed (that costs a lot) and so require testsigning boot option.

For the version you have (probably 0.13.1 or earlier), the only option I guess is to:
 - Stop any application from using SAR ASIO driver if any (like Reaper, Ableton, Jack, ...)
 - Delete SAR configuration in this folder: `%appdata%\SynchronousAudioRouter`
 - Open `device manager`
 - Show hidden devices using `View -> Show Hidden Devices` menu
 - First, browse `Audio inputs and outputs` and uninstall all Synchronous Audio Router related devices
 - Browse `Sound, video and game controllers` and uninstall all SynchronousAudioRouter devices
 - Run SAR uninstaller

**Comment by jester-prawn** [comment]
This issue is not fixed following the included directions does not remove the software.

**Comment by amurzeau** [comment]
Did you tried installing then uninstalling using this version ?
https://github.com/amurzeau/SynchronousAudioRouter/releases/tag/v0.13.99.2-amurzeau

This version's uninstaller will remove more stuff.
I did not found any way to remove the remaining stuff in Windows registry related to endpoint caches or things like that, Windows manage this by itself.

If you find an API or a way to remove the remaining stuff, then the uninstaller will be updated to include them.

**Comment by bradisbell** [comment]
@amurzeau Have you found any way to remove audio endpoints?  I'm working on an unrelated project with the exact same issue... that endpoint registry entries are cached and aren't really removable.

**Comment by amurzeau** [comment]
The remaining cache is here, if that's what you are looking for:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio`
