### ISSUE TITLE
Crash caused by device name

### ISSUE THREAD

**Issue by Yuan-Quan** [eiz/SynchronousAudioRouter#76]
### Crash caused by device name ###
I created a new Windows Audio Device, named it in Chinese.
Now, every time I launch my daw  
and select the ASIO device **SynchronousAudioRouter**
the daw will crash and my system will get stuck for a few seconds  
I reinstalled sar, but it still not working.

**Comment by skaufhold** [comment]
While I can't help fix the issue itself, here's a workaround: Either delete %appdata%\SynchronousAudioRouter\default.json or edit the names in the file.

**Comment by Yuan-Quan** [comment]
> While I can't help fix the issue itself, here's a workaround: Either delete %appdata%\SynchronousAudioRouter\default.json or edit the names in the file. I think that should be enough, unless the issue is something about the audio devices itself that gets left over after uninstall. Then I'm not entirely sure how to fix the issue.

Thanks!!
It works
![image](https://user-images.githubusercontent.com/34994002/64073248-8f1b6080-cc8a-11e9-9f38-046123e7282e.png)
