### ISSUE TITLE
Building or New Release?

### ISSUE THREAD

**Issue by jreben** [eiz/SynchronousAudioRouter#77]
I seen there were 30 commits since last release, some of them sound pretty useful. So I tried to build it.

I didn't see any build instructions, and frankly I have no clue what I am doing with Visual Studio... I tried 2019 it doesn't want to upgrade installer install. The Windows SDK version says it should be VS 2017, but it still fails to upgrade the installer. Something else is also missing because it doesn't seem to be building the driver related stuff. Though I don't see an error.

I am also not seeing a way to generate x64_32 dll that comes in the MSI release, or is this just the 32bit dll?

I usually am all for teaching a man to fish, but I am clueless with WDK. Any chance you would have time to build a new release?

**Comment by amurzeau** [comment]
I've generated a unsigned prerelease here: https://github.com/amurzeau/SynchronousAudioRouter/releases/tag/v0.13.99.2-amurzeau

I'm using that one every day now on Windows 10 1909 without issue, but that require testsigning enabled and maybe also secure boot disabled.

The project is built on appveyor using VS 2017 but require WiX to build the msi installer (which is not included by default with VS 2017).

I don't think VS 2019 is very different appart from a project upgrade.
The x64_32.dll is just the 32 bit DLL. This is to support both 64 bits and 32 bits ASIO applications.
