### ISSUE TITLE
Channel write leak

### ISSUE THREAD

**Issue by veins1** [eiz/SynchronousAudioRouter#79]
I don't know of a better way to name this issue, but what happens is this:
 I have 3 Playback "lines"
A: 6 channels B: 2 channels C: 2 channels
and 1 Record "line"
M: 2 channels

When some app plays 6 channels on A, 2 of them appear on M
What's crazy is that I cannot see it in Reaper, but apps that use M as input device can.
This is definitely not a routing problem; it still happens with all channels muted.

Thanks in advance.

**Comment by amurzeau** [comment]
I can't reproduce this, do you have something enabled in Reaper that could bypass some ASIO inputs to ASIO outputs ?

**Comment by veins1** [comment]
> do you have something enabled in Reaper that could bypass some ASIO inputs to ASIO outputs ?
I don't know of any such settings. I would gladly check them if you know any.

**Comment by veins1** [comment]
I feel so stupid. For some reason I had a hidden track in my project that was causing this. Sorry.
