### ISSUE TITLE
Endpoints not saving

### ISSUE THREAD

**Issue by ilikechickenalotbtw** [eiz/SynchronousAudioRouter#89]
Reaper lanuched with admin

**Comment by amurzeau** [comment]
Renaming audio endpoints cannot always work, this is a limitation of Windows.
You can rename audio endpoints as explaining here https://winaero.com/blog/rename-audio-device-windows-10/

**Comment by ilikechickenalotbtw** [comment]
I'm not trying to rename endpoints, in the SAR control panel, they are not saving.

**Comment by amurzeau** [comment]
This could be related to https://github.com/eiz/SynchronousAudioRouter/issues/53 ?
